### ISSUE TITLE
Red is not properly installed, install and re-run script

### ISSUE THREAD

**Issue by astulaaa** [nextgenusfs/redmask#2]
Hello,

I got this "Red is not properly installed, install and re-run script" and tried to reinstall red (from the website provided) on the server, I did put Red in on the PATH using .bashrc 
Do you have any more specific insights what the issue with Red instalation might be?
Thank you

**Comment by astulaaa** [comment]
I have went around that by installing red with conda. Now I am getting "redmask.py:96: DeprecationWarning: 'U' mode is deprecated
  with open(input, 'rU') as infile:" 
I guess that may be python issue (?). How much in trouble am I?

**Comment by nextgenusfs** [comment]
Not a big deal!  I think I wrote this for py2 and you are likely using python3 which is causing that error.

**Comment by astulaaa** [comment]
Yes, it was Python v3.8.0 indeed. After the job is done I see more in the log file:  "with open(maskedBED, 'rU') as infile:
Traceback (most recent call last):
  File "/anaconda3/envs/RepeatMask_wRED/bin/redmask.py", line 205, in <module>
    outfile.write('>{:}\n{:}\n'.format(name, softwrap(Seq)))
  File "/anaconda3/envs/RepeatMask_wRED/bin/redmask.py", line 121, in softwrap
    for i in xrange(0, len(string), every):
NameError: name 'xrange' is not defined
REDMASK.e228719 (END)" 
I think this all content in the log file has to do with python version incompatibility. As a result .genome_masked.fa.repeats.fasta file is empty, however, .genome_masked.fa.softmasked.fa file seems actually softmasked. If this is expected let's close the issue. Thank you for your time!

**Comment by nextgenusfs** [comment]
Yes xrange is py2 only. When I get a chance I will make py2/3 compatible. In the meantime should be able to just launch the script with python2.

**Comment by astulaaa** [comment]
Just curious, does this python error affect the masking on the sequence ?
